package com.dollop.fos.helper;

public class AppConstant {

	public static final String EMAIL_IN_USE = "Email is already in user.... !!";
//	public static final String UPDATE_USER = "You can't change your email.... !!";
	public static final String USER_NOT_FOUND="user not found....!!";
//	public static final String GENERATED_BY="generated by PIYUSH....!!";
	public static final String RESTAURANT_FOUND = "Restaurant Already Exist...!!";
	public static final String RESTAURANT_NOT_FOUND = "Restaurant Not Found....!!";
	public static final String CATEGORY_NOT_FOUND = "Category Not Found....!!";
	public static final String FOOD_NOT_FOUND = "food not found...!!";
	public static final String FOUND_FOUND = "Food Already Exist...!!";
//	public static final String TABLE_ALREADY_EXIST = "Table Already Exists...!!";
//	public static final String TABLE_NOT_FOUND = "Table Not Found...!!";
//	public static final String TABLE_NO_EXIST = "This No Table Already Exist take anoher no...!!";
//	public static final String REVIEW_NOT_FOUND = "Review Not Found...!!";
//	public static final String CUSTOMER_NOT_FOUND = "Customer Not Found...!!";
//	public static final String CART_EXIST = "This User Cart Already Exist...!!";
//	public static final String CART_ISEMPTY = "Your Cart Is Empty...!!";
	public static final String DUPLICATE_EMAIL = "this Email is already Registered.....";
	public static final String NO_VALUE_PRESENT = "No Value Present in this object...!!";
	public static final String INCARRECT_EMAIL_EXCEPTION = "Your Email Address incorrect...!!";
	public static final String OTP_TIME_EXPIRE = "your OTP time is expire now please regenerate OTP...!!";
//	public static final String TABLE_BOOKED_ALREADY = "Table aready booking...!!";
//	public static final String DATA_NOT_FOUND = "Data Not Found...!!";
	public static final String CATEGORY__FOUND = "Category Already Exist...!!";
//	public static final String ORDER_NOT_FOUND = "Order Not Found..!!";
	public static final String MSG_EXCEPTION = "Exception in progress...!!";
//	public static final String REVIEW_DELETED = "Review Deleted Successfully...!!";
//	public static final String DELETE_SUCCESS = "Delete Suceesfull...!!";
//	public static final String NOT_DELETE = "Not Deleted...!!";
//	
	public static final String RESPONSE_MESSAGE = "message";
//	public static final Object TABLE_DELETE_SUCCESSFULLY = "Table Deleted successfully";
//
//	/*Add Constant*/
	public static final String RESTAURANT_ADD_SUCCESS = "Restaurant Added Successfully..!!";
//	public static final String RESTAURANT_DELETE_SUCCESS = "Restaurant Deleted Successfully..!!";
//	public static final String RESTAURANT_DELETE_FAILED = "Restaurant Deletion Failed..!!";
//	public static final Object TABLE_SAVE_SUCCESSFULLY = "Table Added Successfully..!!";
	public static final Object CATEGORY_ADD_SUCCESS = "Category Added Successfully..!!";
	public static final Object FOOD_ADD_SUCCESS = "Food Added Successfully..!!";
//	public static final Object SUCCESSFULL_ADD_TO_CART = "Item Added Successfully..!!";
//	public static final Object QUANTITY_INCREASE = "Item Quantity Increase..!!";
//	public static final Object WAIT_FOR_CONFIRMATION = "waiting for Admin Approval..!!";
//	public static final Object LIST_OF_USER_NOT_FOUND = "list of Users Not Found..!!";
//	public static final Object LIST_OF_ADMIN_NOT_FOUND = "list of Admin Not Found..!!";
//	public static final Object LIST_OF_CUSTOMER_NOT_FOUND = "list of Customer Not Found..!!";
//	public static final Object LIST_OF_OWNER_NOT_FOUND = "list of Owner Not Found..!!";
//	public static final Object LIST_OF_DELIVERY_BOY_NOT_FOUND = "list of Delivery boy Not Found..!!";
//	
//    /*update Constant*/	
//	public static final Object RESTAURANT_UPDATE_SUCCESS = "Restaurant Update Successfully..!!";
//	public static final Object CATEGORY_UPDATE_SUCCESS="Category Updated Successfully..!!";
//	public static final Object TABLE_UPDATE_SUCCESS = "Table Updated Successfully..!!";
	public static final Object USER_CREATED = " Signup Successfully..!!";
	public static final Object USER_NOT_CREATED = "ERROR in create User..!!";
//	public static final Object FOOD_UPDATE_SUCCESS = "Food Update Successfully..!!";
//	public static final Object USER_UPDATE_FAILED = "User Updation Faild..!!";
//    
//
//	//delete constant
//	public static final Object FOOD_DELETE_SUCCESS = "Food Deleted Successfully..!!";
//	public static final Object USER_DELETE_SUCCESS = "Customer Deleted Successfully..!!";
//	public static final Object USER_DELETE_FAILD = "Customer is not deleted..!!";
//	
////	CHANGE PASSWORD
//	public static final String OLD_PASS_INCORRECT="Your old password was entered incorrectly..!!";
//	public static final String PASSWORD_NOT_VERIFY="New password and Verify password does not match..!!";
//	public static final String PASSWORD_CHANGED="Your password is changed successfuly...!!";
//	// COMMAN
//
	public static final Long OTP_TIME_DIFERENCE = (long) 5;
//	public static final Object REST_UNDO_SUCCESS = "UNDO RESTAURANT...!!";
//	public static final Object SERVER_ERROR = "Something Went Wrong..!!";
//
//
	public static final String DATA = "data";
	public static final String ERROR = "error";
	public static final String TOKEN = "token";
//	public static final String ADMIN = "admin";
//	public static final String BOY = "boy";
//	public static final String CUSTOMER = "customer";
//	public static final String OWNER = "owner";
	public static final String ROLE = "role";
//	
//	
//	
//
//	
//	
	public static final String PROFILEFOLDER = "userPofile";
	public static final String UNVERIFIED = "Unverified";
	public static final String REST_CURR_CLOSE = "Closed";
	public static final String VERIFIED = "Verified";
	public static final Object ALREADY_VERIFIED = "Restaurant Already Verified..!!";
	public static final Object RESTAURANT_VERIFIED_SUCCESSFULLY = "Restaurant Verified SuccessFully..!!";
	public static final String UNBLOCK = "Unblock";
	public static final Object WAIT_FOR_APPROVAL = "Restaurant is UnVarified Wait For Admin Approval..!!";
	public static final Object RESTAURANT_ADDRESS_SAVE = "Restaurant Address Save Successfully..!!";
	public static final Object ADDRESS_ALREADY_SAVE = "Restaurant Address Already Save..!!";
	public static final String BLOCKED = "block";
	public static final Object REST_ALERDY_BLOCK = "Restaurant Already Blocked..!!";
	public static final Object RESTAURANT_BLOCK_SUCCESSFULLY = "Restaurant Block Successfully..!!";
	public static final String REST_ALERDY_UNBLOCK="Restaurant Already UnBlocked..!!";
    public static final String RESTAURANT_UNBLOCK_SUCCESSFULLY="Restauant Already Unblock..!!";
	public static final Object REST_ALREADY_UNVERIFIED = "Restaurant Already UnVerified..!!";
	public static final Object RESTAURANT_UNVERIFIED_SUCCESSFULLY = "Restaurant UnVerified Success..!!";
	public static final Object CATEGORY_UPDATE_SUCCESS = "Category update Success....!!";
	public static final Object RESTAURANT_UNVERIFIED = "This Restaurant is Unverified....!!";

	public static final String EMAIL_ALREADY_REGISTERED = "1231";

	
	
	
//	*****
//	public static final String RESTAURANT_NOT_FOUND
	
	
	

	

	


	
}
